### ISSUE TITLE
Not centering icons

### ISSUE THREAD

**Issue by Baesmuth** [ChrisAnd1998/TaskbarX#197]
Instead of centering the icons it moves them to the right side of my taskbar.

**Comment by Baesmuth** [comment]
my friend has the same problem, he had to set the offset to -66 and I had to set it at -375

**Comment by Baesmuth** [comment]
Now it sometimes isn't centering and it seems like it has 1-3s delay
https://i.imgur.com/7OF58zv.mp4

**Comment by ChrisAnd1998** [comment]
Did you use the old manual method before using FalconX? If so you need to remove that toolbar.

**Comment by Baesmuth** [comment]
can you explain? what old way?

**Comment by ChrisAnd1998** [comment]
This method 

https://www.wisecleaner.com/how-to/111-how-to-center-the-taskbar-icons-in-windows-10.html

It will allow you to move the taskbar to a certain position but won't update it's self of course.

**Comment by Baesmuth** [comment]
the sad thing is that it doesn't move itself to the middle, it's the only reason im using falconX :v

**Comment by ChrisAnd1998** [comment]
Also the reason why i made FalconX. XD

**Comment by JPHFanedits** [comment]
just started using FalconX and am experiencing the same issue after updating to the latest version

**Comment by ChrisAnd1998** [comment]
I am currently rewriting to whole project.
Does this fix it already?
https://github.com/ChrisAnd1998/FalconX-Center-Taskbar/files/4363343/Debug_v2.zip

**Comment by Cabola** [comment]
Technically mine haven't worked "correctly" since beginning of v1.4. I have 3 monitors and they're setup like this
![Untitled-1](https://user-images.githubusercontent.com/19853946/79461625-b6932380-7ff6-11ea-8cd6-590f34b834de.png)
My task bar doesn't center on any of them after startup till I have a program open on monitor 2 and 3. Now it's not that big a deal because I have my mail open on monitor 2 and Discord on monitor 3. So when they startup and open up, the icons on each taskbars on all 3 monitors move to the center.

But if I don't open my mail program or any other program on monitor 2 then all 3 taskbars icons will remain in the left side. Mind you I only have icons showing on monitor 1 (primary) and then any open programs icons will display on their respective monitors taskbar. This is where I think the bug is to be found. Because when my windows boot up and FalconX/TaskbarX is ran there's no icons to move on monitor 2 and 3 so therefor it doesn't execute anything even tho there's icons on the primary monitors taskbar. Well that's my theory anyways...

**Comment by ChrisAnd1998** [comment]
@Cabola Did a lot of testing this is what i cam up with.
[Test.zip](https://github.com/ChrisAnd1998/TaskbarX/files/4487577/Test.zip)

**Comment by Cabola** [comment]
@ChrisAnd1998 That worked perfectly! Now it centers by it self from start! w00p w00p! Thank you..

**Comment by ChrisAnd1998** [comment]
@Cabola Great!!!
