### ISSUE TITLE
[Feature Request] Battery Optimization

### ISSUE THREAD

**Issue by solariz** [ChrisAnd1998/TaskbarX#210]
Hey,

when you currently rewriting the code maybe a good Input for Future Version.
It would be great to have a "On Battery" Setting in the Settings causing a less agressive refresh time, optionaly disable animations and decorations when System runs ons Battery.

👍

**Comment by ChrisAnd1998** [comment]
Hi @solariz, Did you experience a battery drain on the default settings?
Because it's power consumption is already almost nothing or at least i am not noticing any difference on my laptop... I really appreciate the feature request but, i'm not sure if it would make a difference.

I could make the option to have alternative settings when running on battery not on power.
Like "-onbatterylooprefreshrate=1000" and "-onbatteryanimationstyle=none"

**Comment by solariz** [comment]
That's actually what I meant. Actually only needed for refresh time and decoration.

Drain; not really a proof but I tend to minimize all eye candy when I'm on battery and currently for falcon that means changing all my preset settings and later redo them. A feature for settings with and without battery mode on would just be a bug usability improvement for those like me who need to rely on each minute battery sometimes.

But definitely no high priority thing.

**Comment by ChrisAnd1998** [comment]
I have added it to the pre-release v8 ;)
https://github.com/ChrisAnd1998/FalconX-Center-Taskbar/releases/tag/1.5.0.0
