### ISSUE TITLE
Windows detects the installer as malware/unsafe

### ISSUE THREAD

**Issue by entelex29** [ChrisAnd1998/TaskbarX#226]
I ran into this issue when downloading the installer for the new TaskbarX update from your website (https://chrisandriessen.nl/web/taskbarx/). Windows seems to mark the installer.exe as unsafe, prompting multiple checks to install it. 

When downloading using Microsoft Edge (Chromium):
Microsoft Defender SmartScreen reported that this app is not commonly downloaded or is not signed by its publisher.
Name: TaskbarX_1.5.2.0_Setup.exe
Publisher: Unknown

When installing:
App: | TaskbarX_1.5.2.0_Setup (1).exe
-- | --
Publisher: | Unknown publisher

Just letting you know that this is something I ran into.

**Comment by Lukas34** [comment]
I think that's because the Software is unsigned.

You see, when publishing Windows applications, one needs an Extended Verification (EV) Certificate, which is used to verify that you have published that application. The special thing about EV certificates is that a third party company like Digicert or GlobalSign will verify that you are the person you say you are.
If you then publish some software and sign it with that certificate, anyone can look at the signed software and ask the trusted third party if the certificate is legit. That way, no one can publish software under your name or at least can't sign it with your name as the third party would see that you are not that person so they won't give you a certificate.

Windows requires software to have such an EV certificate, otherwise they will show an "Unknown publisher" warning, as they can't tell if you really published that software.

That whole certificate thing is very great for security but bad for individuals as these EV certificates cost a lot of money and have to be renewed yearly. Digicert for example, wants $664 a year and GlobalSign $410 a year. And especially for (smaller) open source projects, it is often just not worth it to pay so much money for free software.
_I might also be wrong here, that's only what I know from my research._

**Comment by ChrisAnd1998** [comment]
It's right what @Lukas34 explained certifications are very expensive and indeed just not worth it.
However after some time when many people have been using it the false positives will dissapear.
