### ISSUE TITLE
[Feature Request] Chocolatey installer

### ISSUE THREAD

**Issue by KuraiAndras** [ChrisAnd1998/TaskbarX#272]
Can you maintain a [chocolatey](https://chocolatey.org/) package of this program? It would make installing this even simpler. [Docs](https://chocolatey.org/docs/create-packages)

**Comment by benjivm** [comment]
While it isn't what you're asking for [Scoop](https://scoop.sh)'s [extras bucket](https://github.com/lukesampson/scoop-extras) [includes TaskbarX](https://github.com/lukesampson/scoop-extras/blob/master/bucket/taskbarx.json). I dropped [Chocolately in favor of Scoop](https://github.com/lukesampson/scoop/wiki/Chocolatey-Comparison) because it works quite a lot better in my experience and most of the packages are updated much faster.
