### ISSUE TITLE
Please use alternative auto start techniques instead of task scheduler

### ISSUE THREAD

**Issue by wanderseeme** [ChrisAnd1998/TaskbarX#301]
As far as I'm concerned, every time I start my Windows, the black cmd window shows up and starts the TaskbarX, which is quite not as elegant as other Store apps (such as QuickLook, Snipaste, ...)

So would you please use alternative auto start techniques (like the ones used by QuickLook and Snipaste, maybe?) instead of task scheduler?

**Comment by ChrisAnd1998** [comment]
Problem is that it needs to be started as quick as possible. This can only be done using the taskscheduler. To run a Microsoft Store app i cant just call the exe file because, that does not work. Instead i'am forced to use a shellapp: command to run TaskbarX. This can be done through cmd.exe and explorer.exe. explorer.exe doesn't always work so it needs to be done using cmd.

**Comment by TheFruxz** [comment]
Right @ChrisAnd1998, currently the software starts mercilessly fast, so I don't see any time lag between OS start and taskbar start (in my MS-Store version, I don't have others)

**Comment by wanderseeme** [comment]
Thanks for you response!

Using cmd to start this app is OK, is there any way to run cmd in background? Just please do not pop up a black cmd window every time the computer starts, which makes the starting procedurae  little bit annoying.
