### ISSUE TITLE
[Bug]Class not registered error on boot up

### ISSUE THREAD

**Issue by onlytanmoy** [ChrisAnd1998/TaskbarX#304]
Hey Chris @ChrisAnd1998 - hope all ok at your end.
please see below screenshot for the issue I am facing
https://imgur.com/a/P5GLVQI
This is happening quite often now while I start my machine in the morning.
On clicking OK, I get the default windows taskbar.
The only way to get TaskbarX back is then to open it via Windows start.

**Comment by ChrisAnd1998** [comment]
@onlytanmoy Hi, everything is ok :)
This mostly happens when people try to uninstall TaskbarX without removing the taskschedule. I assume you still want to use TaskbarX so what you can try to do is open the configurator and go to the Taskschedule tab. In that tab you will see a delay option. Try to increase that value with a couple seconds and see if that fixes it.

**Comment by onlytanmoy** [comment]
@ChrisAnd1998 yes Chris, I most certainly want to continue using TaskbarX (one of my favourites), so I increased the value from 3 to 7 in the Taskschedule tab, hopefully this will take care of the issue.
Can I have this ticket remain open for couple of days and then I close down?

**Comment by ChrisAnd1998** [comment]
@onlytanmoy Yes of course... Hope that fixes the issue.

**Comment by onlytanmoy** [comment]
@ChrisAnd1998 I got that pop-up again today at start up :( increased the time out to 10 now.
Do you recommend uninstalling TaskbarX and then install back again?

**Comment by onlytanmoy** [comment]
Seems to be working fine now :) Will close this ticket now. Thanks mate.
