### ISSUE TITLE
Taskbar Style not applied on Windows startup

### ISSUE THREAD

**Issue by kaabkb** [ChrisAnd1998/TaskbarX#315]
TaskbarX centers the icons but doesn't go transparent on startup, I have to open the TaskbarX Configurator and then I have to go to the Style tab and then click on apply. Then it goes transparent.

**Comment by dianasebo** [comment]
The same happens to me. I'm running version `1.5.6.0`.

**Comment by NicTanghe** [comment]
Also happening to me I can't restart the app because I don't remember where I unpacked the zip :/

I must note other programs that start at startup failed functioning but not launching. Namely:
Power toys, aurora.

PS. Aurora often fails to function on startup but normally the others then don't break.
it has happend on occasion with powertoys maybe taskbarX also crashed back then (dont c a corresponding ticket on their Issues.

**Comment by SkyrenOfficial** [comment]
Facing very same issue with v1.5.8.0 (latest). Also have to open TaskbarX Configurator and "Apply" Style.

**Comment by SkyrenOfficial** [comment]
Facing very same issue with v1.5.8.0 (latest). Also have to open TaskbarX Configurator and "Apply" Style to make it Transparent.

**Comment by Parth-Mawai** [comment]
same happens with me

**Comment by Fefedu973** [comment]
Same

**Comment by esamelsaket** [comment]
Same happens with me it doesn't go opaque and disappear the startup button on startup

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
