### ISSUE TITLE
Glitchy appearance when used with Auto Dark Mode

### ISSUE THREAD

**Issue by KatakisLives** [ChrisAnd1998/TaskbarX#316]
I noticed that Taskbar X seems to blink a little erratically when the software for Auto Dark Mode changes the Windows 10 theme. I'm not sure if it's a good idea to report this bug here or if I should do so to the developers of Auto Dark Mode, so I hope it's alright to report this bug here.

**Comment by Tminus1** [comment]
Does this bug occur when you're manually switching the theme from the settings? If not, report it to the Auto Dark Mode team too just to be sure.

**Comment by ChrisAnd1998** [comment]
@KatakisLives Well, when switching to dark mode or changing anything else to your Windows theme some of those messages will be send to the Shell (Explorer.exe):
**WM_DWMCOLORIZATIONCOLORCHANGED
WM_DWMCOMPOSITIONCHANGED
WM_THEMECHANGED**
Causing the taskbar to completely reset itself making it go back to it's default position (Left). The taskbar style will also be reset to it's default color. The glitchy effect happens because, of the reset and TaskbarX setting it back to the center and reapplying the taskbar style. I have found a way to keep the icons at their position by blocking the redraw of the taskbar's parent but that does not work for the taskbar style as it will freeze the whole taskbar. I may find a solution for this in the future...

**Comment by KatakisLives** [comment]
I see, now. Thanks for letting me know about this.

(Sorry for my delay in responding, BTW)
