### ISSUE TITLE
[Request] Newer update should be released first to Microsoft Store users.

### ISSUE THREAD

**Issue by btdat2506** [ChrisAnd1998/TaskbarX#367]
Microsoft Store users are users who donated for the project. The project is great and awesome, I like it a lot but I can't deny the fact that the Store users are not getting the latest update like Github users, which make us feel a bit unhappy as we can't have the latest features and fix

**Comment by ChrisAnd1998** [comment]
Thanks :) I understand this could be frustrating but, the problem is that there is a 3 working day delay for Microsoft to publish it to the store. I really don't want to wait for releasing new updates after they are published to the store. I actually think it's better this way as if there is something wrong with a new update github users can report those issues and i can fix them before it gets published to the store. Making sure you have the best experience.

If this process gets faster in the future then i can consider publishing updates to the store first.

**Comment by btdat2506** [comment]
> Thanks :) I understand this could be frustrating but, the problem is that there is a 3 working day delay for Microsoft to publish it to the store. I really don't want to wait for releasing new updates after they are published to the store. I actually think it's better this way as if there is something wrong with a new update github users can report those issues and i can fix them before it gets published to the store. Making sure you have the best experience.
> 
> If this process gets faster in the future then i can consider publishing updates to the store first.

Well, I guess now I know about the "3 days delay" of Microsoft, I think that maybe no more misunderstood anymore. I guess you can close the issue if you want to, and thanks for the explanation. Have a good day!
