### ISSUE TITLE
Unable to Uninstall

### ISSUE THREAD

**Issue by alexeidrekker** [ChrisAnd1998/TaskbarX#373]
I have version 1.5.7.0 installed that I got from Github. It had the Taskbar X Installer file that I used to install it. Unfortunately, that file has disappeared in both the latest version, and the version history on Github. I went to my installed programs and tried uninstalling from there which resulted in an error message stating that I did not have sufficient access. I am the admin though. All other apps uninstall correctly. Going to the location of the app and clicking on the Taskbar X installer file just leads to another error stating that an unhandled exception has occurred. Not sure what to do from here. I have attached two screenshots for your reference. 
![image](https://user-images.githubusercontent.com/68187312/91304492-8fecb280-e777-11ea-81ae-3dd1b3790292.png)

![image](https://user-images.githubusercontent.com/68187312/91304632-cc201300-e777-11ea-94e5-9ffc1f4357ba.png)

**Comment by alexeidrekker** [comment]
Manually removed the app. I will probably go to the Windows Store version now. Not sure if I should close this issue because it appears the problem might still exist. I will leave the decision up to you. Thanks.

**Comment by ChrisAnd1998** [comment]
@alexeidrekker Yep, the installer is gone for now because i couldn't get it to work stable yet.

**Comment by Cyberdroid1** [comment]
This might be an old issue, but I have this ghost entry in the Apps and Features page.
![image](https://user-images.githubusercontent.com/51435948/124962844-b9839500-e03c-11eb-80fc-e4e4ccb8ef05.png)

I am not able to remove it, since selecting it and clicking on uninstall brings up another error
![image](https://user-images.githubusercontent.com/51435948/124962940-d8822700-e03c-11eb-89e8-29ee1e0b529e.png)

How do i remove this entry?
