### ISSUE TITLE
Taskbar on 2nd monitor is transparent

### ISSUE THREAD

**Issue by 28925** [ChrisAnd1998/TaskbarX#402]
When setting the taskbar mode to "blur" (or any other mode bar default), the primary monitor will display it correctly; however, secondary taskbar will be displayed as transparent 

![image](https://user-images.githubusercontent.com/71497724/93590093-44819900-f9f1-11ea-94fa-67338183e8e5.png)

![image](https://user-images.githubusercontent.com/71497724/93590097-464b5c80-f9f1-11ea-86db-cfe5115b747a.png)

**Comment by JK8MQ** [comment]
Have the same issue, for me, it happens when I have auto-hide enabled, and only the taskbars that can be seen at the moment of restarting TaskbarX have proper blur while the ones that hide, only have the weird blur at the top, while keeping the rest un-blurred and just transparent. The same visual glitch happens when selecting Acrylic.

It looks like turning off windows auto-hide is the only way to fix this issue at the moment.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
