### ISSUE TITLE
Taskbar X not working 

### ISSUE THREAD

**Issue by Rigalur** [ChrisAnd1998/TaskbarX#406]
Taskbar X doesn't work when I try to open it, when I open the console, it said something like umm"missing method....." something like that, please help I can't use it

**Comment by ChrisAnd1998** [comment]
@Rigalur I can try to help but, i need to know exactly what message the console gave... Or even better follow this
https://github.com/ChrisAnd1998/TaskbarX/issues/274

**Comment by Rigalur** [comment]
@ChrisAnd1998 Hi, the console said 
"Waiting for Shell_Traywnd
65748
@Looper1 | Error: Missing method 'instance object [TaskbarX] Accessibility.IAccessible: :get_accRole(object)' from class 'System.Int32"

**Comment by qthang** [comment]
i have same problem

**Comment by RubenMLL** [comment]
x3

**Comment by qthang** [comment]
> i have same problem
ver 1.5.4.0 maybe use

**Comment by RubenMLL** [comment]
> > i have same problem
> 
> ver 1.5.4.0 maybe use
> 
> 

My version is 1.6.1.0 but I tried with old versions and neither

**Comment by qthang** [comment]
I tried with old versions and it run

**Comment by RubenMLL** [comment]
> I tried with old versions and it run

Well, later I will test exactly that version in case it works

**Comment by alexrps96** [comment]
i have the same problem and only 1.5.2.0 worked for me, i have the latest windows 10 64 bit update and im with the Home Edition.

**Comment by almightyju** [comment]
@ChrisAnd1998 So I ran into this today and it seemed to start after I uninstalled some programs, I expect a restart might fix it but decided to look into it anyway. It looks like for some reason MSAA.GetAccessibleChildren is returning an array that has some int values rather than com objects, I don't have time to look into it myself but it might just be a case of type checking before callingchildx.get_accRole 

Adding some screenshots of dnSpy which should hopefully help out :)
<img width="1185" alt="children are ints" src="https://user-images.githubusercontent.com/7722347/117647746-487f4880-b185-11eb-9c92-3e4bd3efed3f.png">
<img width="754" alt="TaskObjects are accessibles" src="https://user-images.githubusercontent.com/7722347/117647749-49b07580-b185-11eb-80a9-c4dbd9f82875.png">

**Comment by vinbreauX** [comment]
I have the same error, which started right after today's Windows 10 update. Oddly, it's working on my laptop screen but not my 2nd monitor. Clicking Restart TaskbarX just opens that shell screen with the error.

So it does work on one screen but not the external screen.

![image](https://user-images.githubusercontent.com/2532176/121746082-8e039e00-cac2-11eb-8e1b-b2f3891b06f6.png)

**Comment by vinbreauX** [comment]
I noticed that the weather icon at the lower-left corner that was not there prior to the update. I turned it off and now TaskbarX is working... but the shell window with the error still appears.

![image](https://user-images.githubusercontent.com/2532176/121749259-97dbd000-cac7-11eb-8138-aff624d5e499.png)

**Comment by Dragon4games** [comment]
> I noticed that the weather icon at the lower-left corner that was not there prior to the update. I turned it off and now TaskbarX is working... but the shell window with the error still appears.
> 
> ![image](https://user-images.githubusercontent.com/2532176/121749259-97dbd000-cac7-11eb-8138-aff624d5e499.png)

same problem but when i turn off the weather it still doesnt work

**Comment by shayvt** [comment]
Check that your taskbar has at least one hidden icon.
I noticed that if all of them are visible you will get this error.

![image](https://user-images.githubusercontent.com/6310671/123432015-97b4f780-d5d2-11eb-8734-a97ca787da8d.png)

**Comment by Dragon4games** [comment]
> > I noticed that the weather icon at the lower-left corner that was not there prior to the update. I turned it off and now TaskbarX is working... but the shell window with the error still appears.
> > ![image](https://user-images.githubusercontent.com/2532176/121749259-97dbd000-cac7-11eb-8138-aff624d5e499.png)
> 
> same problem but when i turn off the weather it still doesnt work. and i noticed that the configurator doesnt store my settings if i open it it just goes back to default

I fixed it the problem somehow was that I was opening taskbar x and the configuration from the search bar if I opened it from the files everything worked as normal

**Comment by Lolarent000** [comment]
I'm running windows 10 and it's been stopping working for me for a while. I find if I restart it, it works but only while the command prompt window is open (showing "Waiting for Shell_TrayWnd"). Show console is not ticked in the TaskbarX configurator.

No idea what the issue is here. Was working until recently. I have it installed through the microsoft store if that makes a difference.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
