### ISSUE TITLE
Start/Search/Cortana Icons are black

### ISSUE THREAD

**Issue by evannilaz-zz** [ChrisAnd1998/TaskbarX#430]
When I enable TaskbarX on Light mode, System icons on taskbar remain black. I think it would be better to change Windows mode to dark automatically or just show an alert.

**Comment by Cyberdroid1** [comment]
You might have changed taskbar appearance to opaque, thats why you might be facing this problem.

**Comment by elitance** [comment]
@Cyberdroid1 I'm not reporting a bug, but *suggesting* an idea. I'm suggesting to change Windows system theme to Dark automatically (if TaskbarX's theme is not Windows Default) because some people might struggle with this, racking his head. System taskbar icons on taskbar remain black when I enable TaskbarX with Light theme enabled in Windows system.

**Comment by Cyberdroid1** [comment]
Ah ok, sorry for misinterpretation. I agree with that point. It would be better to give a warning, rather than directly change it, since it also changes the appearance of start menu.
