### ISSUE TITLE
Unattended installation

### ISSUE THREAD

**Issue by pratyakshm** [ChrisAnd1998/TaskbarX#445]
I tried installing TaskbarX in an unattended manner - I used the switches `/quiet /norestart` but it still opens the GUI installer waiting for the user to prompt. Can you add support for silent installation in future releases of TaskbarX? If so, I would be able to create a PR in **winget** repository to merge TaskbarX's manifest. 
Thanks.

**Comment by ChrisAnd1998** [comment]
@pratyakshm That's very nice! however i'm not sure if i will include an msi installer yet.

**Comment by pratyakshm** [comment]
okay, thank you.

**Comment by watermarkhu** [comment]
An new installer would be great. On my work machine Windows store is locked and smart screen prevents me using the zip. A local installation which doesn't require admin privileges would be great.

**Comment by ChrisAnd1998** [comment]
@watermarkhu If the portable zip gets blocked then an installer with the same files will be blocked too :/

**Comment by watermarkhu** [comment]
Does TaskbarX require admin privileges to run? If not, an installer which installs to AppData in stead of Program Files would allow it to run.

**Comment by yashpalgoyal1304** [comment]
the input at https://github.com/ChrisAnd1998/TaskbarX/issues/441#issuecomment-716104630 says slightly different thing. which one's right 🤔 ?

**Comment by yashpalgoyal1304** [comment]
anyways, coming from ["Modernize ...."](https://www.youtube.com/watch?v=GzqIzBn5WLA&t=8m14s) ; just wanted to thank you. i have been searching for a way to fully transparent the taskbar for yearrrs (since 2013-14 i guess) and just found it. What more, it can also center them. Awesommme. If the installer were there, then that would be next awesome thing. Thanks a tonne for providing this great thing :) <3 <3 <3
