### ISSUE TITLE
I have a weird problem. I'm using a Windows 7 Aero theme but to the left and right of the centered taskbar is a strip darker than it should be.

### ISSUE THREAD

**Issue by Kubamach** [ChrisAnd1998/TaskbarX#450]
Here is a screenshot of the problem
![image](https://user-images.githubusercontent.com/69034405/97810685-0e813700-1c76-11eb-9111-974884ace828.png)
.

**Comment by ChrisAnd1998** [comment]
@Kubamach It looks like every panel inside the taskbar gets themed differently. TaskbarX has to move those panels in order to center the taskbar. So this is unfixable. You can try to edit the custom theme and make the color for all panels equal.

Shell_TrayWnd: Dark
MSTaskSwWClass: Dark
MSTaskListWClass: Light
