### ISSUE TITLE
It doesn't centre if you make the task bar too high

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [ChrisAnd1998/TaskbarX#478]
How to reproduce:
1. unlock task bar
2. drag it up to about 40% of your screen height
3. restart TaskbarX
4. it will remain on the left always

**Comment by ChrisAnd1998** [comment]
If the taskbar(s) height goes over 200px then TaskbarX thinks the taskbar is vertical.

**Comment by asdsadsaasd12312132** [comment]
One temporary fix I found was dragging the task bar to the bottom then back up but it gets reset eventually. Maybe this can be implemented somehow?

**Comment by ChrisAnd1998** [comment]
@asdsadsaasd12312132 Should be fixed now in [1.6.4.0](https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.4.0). Instead of checking if the taskbar is higher than 200px it now checks if the taskbar(s) height is higher than the taskbar(s) width. If it is higher then the taskbar should be vertical if not then horizontal.
