### ISSUE TITLE
So my problem is that after I restart my pc taskbarx wont work properly even if I disable it in task scheduler and open it manually. The only way I can make it work again is by pressing TaskbarX configurator and doing all the configurations again and reopening taskbarx.

### ISSUE THREAD

**Issue by Juniorcwl** [ChrisAnd1998/TaskbarX#491]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 1909]

**Additional context**

**Comment by agentvei** [comment]
Hmm, this problem happens to me too.
So, it happens whenever I shut my laptop down or restart it.
Whenever I boot up my laptop again, TaskbarX will not start unless I click the TaskbarX Configurator. It used to work before, but now it does not.
I have tried uninstalling and reinstallongTaskbarX, yet it does not work.
I put the task schedule to 20 seconds instead of 15, but it still does not work.

I am running Windows 10 Version 1909 on a HP Pavilion G4.
Please fix this bug/issue soon, I am tired of starting TaskbarX manually.

**Comment by ChrisAnd1998** [comment]
The only way TaskbarX won't run is because the delay is too short or some Antivirus software blocks the taskschedule.
in most cases (99%) a 6 second delay is fine.

**Comment by agentvei** [comment]
> The only way TaskbarX won't run is because the delay is too short or some Antivirus software blocks the taskschedule.
> in most cases (99%) a 6 second delay is fine.

I don't have any antivirus installed on my PC. Anyway, The TaskbarX app won't run on startup (maybe because my PC is old...) so I just installed the Rainmeter skin. It works perfectly.

Anyway, keep up the great work! I love TaskbarX so much.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
