### ISSUE TITLE
bug after restart

### ISSUE THREAD

**Issue by burakk3** [ChrisAnd1998/TaskbarX#513]
i just recently factory reset my pc so all my stuff is up to date.
every time i switch on my pc or restart mt pc i always get this bug. like everytime. ive deleted the app and downloaded it several times and even when i dont have the app installed i still get the bug. 
i have no way to stop this from happening and its getting really annoying now. please can someone help me fix this.
![unknown](https://user-images.githubusercontent.com/77121817/103932402-b1907a00-5119-11eb-805a-21ca4248019d.png)

**Comment by ChrisAnd1998** [comment]
@burrak3 This only happens with the store version. When uninstalling it the wrong way you will get this message because the Taskschedule won't be removed. There is lots of documentation about this on my website and the github main page. Inside the Configurator you can also use the uninstall tab to properly remove it.
