### ISSUE TITLE
Taskbar just disappearing on startup and taskbar on second a third monitor jumping back and forward

### ISSUE THREAD

**Issue by Hyperra1n** [ChrisAnd1998/TaskbarX#531]
**Describe the bug**
I've been using TaskBarX for a while and never had any issues but today when I started up my pc my taskbar went to center itself and then it didn't stop which caused it to go offscreen, it also didn't go on my second monitor. I also noticed that any taskbar icons I have on the other screen seem to just go back and forward from the center to the edge

I'm not sure how to reproduce this bug since I also tried reinstalling it and it's still happening with completely default settings

**Expected behavior**
I expected the taskbar to go to the middle 

**Screenshots**
![Desktop Screenshot 2021 01 16 - 15 34 48 50](https://user-images.githubusercontent.com/49101934/104813260-bd162c00-5810-11eb-8b58-f235baa68c5b.png)
![Screenshot 2021-01-16 182803](https://user-images.githubusercontent.com/49101934/104817269-e80c7a00-5828-11eb-81ab-cd7ec2e13288.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: 20H2
 - OS build: 19042.746
 - Version: Regular
 - Any other taskbar programs: I had TranslucentTB but I tried it out it and still the same bug

**Additional context**

https://user-images.githubusercontent.com/49101934/104817369-84cf1780-5829-11eb-8b94-33dc681f093c.mp4

**Comment by ChrisAnd1998** [comment]
@Hyperra1n This is a very rare issue and I sadly have not found a solution for this yet. I'm running the exact same build as you so that's not the issue.. To find a fix for this i need to reproduce it.

This Powershell command will dump a list of installed software:
`Get-ItemProperty HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* | Select-Object DisplayName, DisplayVersion, Publisher, InstallDate | Format-Table –AutoSize`

**Source:** https://www.howtogeek.com/165293/how-to-get-a-list-of-software-installed-on-your-pc-with-a-single-command/

Just like this:
[output.txt](https://github.com/ChrisAnd1998/TaskbarX/files/5825962/output.txt)

What i can try to do is build a Virtual Machine with all the same software installed like you. And maybe with a bit of luck the issue will then be reproducible and fixable.

**Comment by Hyperra1n** [comment]
My problem fixed itself today when I started up my pc, which is odd because yesterday nothing changed after 3 restarts. But I'm gonna go ahead and but my dump file here anyway.
[output.txt](https://github.com/ChrisAnd1998/TaskbarX/files/5826177/output.txt)

**Comment by ChrisAnd1998** [comment]
@Hyperra1n It's just magic 🧙😆. Thanks for uploading anyway I will give it a try.
