### ISSUE TITLE
Almost all bugs (ver1.6.6.0)

### ISSUE THREAD

**Issue by zedzenon** [ChrisAnd1998/TaskbarX#544]
I think these are bugs in this version

1.In **Blur mode**, the Start menu works properly. But changing the background is delayed
2.In **Aclyric mode**, the Start menu flashes. But changing the background is not a problem
3.Task view . . ?????? .
👇👇👇👇👇
https://vimeo.com/507094166

**Thank.**

**Comment by alpetrus** [comment]
It would be good to remove item from ALT+TAB (WIN+TAB).

**Comment by zedzenon** [comment]
> It would be good to remove item from ALT+TAB (WIN+TAB).

Yes . I agree

**Comment by ChrisAnd1998** [comment]
@alpetrus It's fixed in the pre release 1.6.6.0

**Comment by alpetrus** [comment]
@ChrisAnd1998 Thanks. I'll wait for the update in the Microsoft Store.

**Comment by zedzenon** [comment]
> @alpetrus It's fixed in the pre release 1.6.6.0

All these problems👉[https://vimeo.com/507094166](url) **or** just the **Alt+Tab** problem.

**Comment by caesarali** [comment]
My taskbar isn't showing in other virtual desktop, just showing in main virtual desktop..
How to solve this bug ? or How to downgrade to previous version for microsoft store version ?

**Comment by ChrisAnd1998** [comment]
@zedzenon What @alpetrus mentioned.. (The ALT-TAB issue)

@ceasarali It's already fixed i the upcoming update 1.6.6.0 ;) Wait for the update to arrive to the store.

**Comment by zedzenon** [comment]
These problems still exist in version 1.6.6, did you watch this video? 👉 https://vimeo.com/507094166

**Comment by ChrisAnd1998** [comment]
@zedzenon I watched.. but i think I won't be able to fix this. The Acrylic flickers because the taskbar constantly refreshes itself when this style is applied. Transparent and blur are fine. The second issue is the same problem it's how the taskbar responds to getting styled. The only way to fix both issues to use a completely different way of styling the taskbar but there is no other known way to do this without dll injection. I am experimenting with drawing panels inside the taskbar but it freezes the taskbar. If i find out how to do it properly then you can do basically everything with the taskbars background without bugs.

**Comment by alpetrus** [comment]
@ChrisAnd1998 TaskbarX updated from MS Store - "problem" with Alt+Tab (Win+Tab) solved. Thanks!

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
