### ISSUE TITLE
TaskbarX icons duplication in the tray.

### ISSUE THREAD

**Issue by Iipal** [ChrisAnd1998/TaskbarX#561]
I don't actually know why, but mostly it's happening when full-screen apps running but that's annoying.
![image](https://user-images.githubusercontent.com/31858171/108372583-d285c980-71b3-11eb-9aa8-ed71010045b8.png)

Also check comments on [this issue with taskbar in Alt+Tab](https://github.com/ChrisAnd1998/TaskbarX/issues/542). It's not fixed yet.

**Comment by itsmeow** [comment]
Just a note on this, this also happens when the app exits/restarts automatically from a crash (what was previously "Taskbar handle not found". The icons in the action bar don't disappear after the restart, and when you hover over them all of them except the new/running one disappear). Don't know if this is related, but I'll see if 1.6.7.0 fixes this as well.
