### ISSUE TITLE
Task Scheduler not working

### ISSUE THREAD

**Issue by JasonN-1** [ChrisAnd1998/TaskbarX#571]
**Describe the bug**
Whenever I make a task schedule, it doesn't create one. It's doesn't save my settings nor does it startup automatically. I went to my Task Scheduler app and it didn't show up. 

**To Reproduce**
1. Go to Taskbarx
2. Click on 'Task Schedule'
3. Scroll down to 'Create Task Schedule'
4. See error (it doesn't create one)

**Expected behavior**
Making a task scheduler, saving my settings, and starting up after every reboot.
**Screenshots**

Video demonstration : [https://youtu.be/P3U5HTQ31mw](https://youtu.be/P3U5HTQ31mw)
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1904

**Additional context**

**Comment by ChrisAnd1998** [comment]
Try manually deleting the taskschedule and then let TaskbarX create a new one. This issue happens when running the Configurator as Admin. https://www.youtube.com/watch?v=QtvxF1S7Dsw

**Comment by JasonN-1** [comment]
I cannot delete the task schedule due to there isn't one.

**Comment by ChrisAnd1998** [comment]
Are you sure? If i watch your video you let TaskbarX create a taskschedule however you're not refreshing the Taskscheduler and scrolling down to see if it's there. You can also try running the Configurator as Admin. And if that works you should run the Configurator as Admin always. Otherwise it will have issues writing to the task. If Admin doesn't work something in your Windows 10 installation is configured wrongly like permissions. Or maybe your'e running an Antivirus that prevents TaskbarX from creating a taskschedule...

![Untitled](https://user-images.githubusercontent.com/50437199/111863829-080e0600-895e-11eb-8d13-53c84182756c.png)
![Untitlesd](https://user-images.githubusercontent.com/50437199/111863832-0a706000-895e-11eb-94c0-8c57ac65804a.png)

**Comment by ChrisAnd1998** [comment]
Looking at your vid and i can see youré using both Bitdefender and Malwarebytes. This could be the issue...
![Untitlssed](https://user-images.githubusercontent.com/50437199/111864132-8b7c2700-895f-11eb-9ccd-84b2166f5750.png)

**Comment by JasonN-1** [comment]
I don't have the Malwarebytes active protection on, and I'll try uninstalling bitdefender. Yes I have checked that there isn't any Taskbarx

**Comment by JasonN-1** [comment]
https://www.youtube.com/watch?v=MGWbQUc6GDw

**Comment by ChrisAnd1998** [comment]
I see, what's the name of your PC and user? Maybe it contains unsupported characters.. 

For example.
PC name: Desktop-R2I36SR 
User: Chris

TaskbarX uses this library to create and modify scheduled tasks https://github.com/dahall/TaskScheduler

**Comment by rashil2000** [comment]
![image](https://user-images.githubusercontent.com/46838874/112426287-b6022180-8d5d-11eb-9acf-447892baba4d.png)

I'm having the same issue since the last update. I have tried manually deleting the task and recreating it, but nothing happens.

(This screenshot shows that the task did run as scheduled, but TaskbarX didn't launch for some reason)

**Comment by JasonN-1** [comment]
PC name: Jason
User: Jason Nguyen

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
