### ISSUE TITLE
Window moving by itself.... Is this an intentional feature??? 

### ISSUE THREAD

**Issue by Spud18** [ChrisAnd1998/TaskbarX#580]
**Describe the bug**
When trying to move the TaskbarX configurator, it moves with a mind of its own.

**To Reproduce**
Steps to reproduce the behaviour:
1. Move the Window.

**Expected behaviour**
You expect it to move where you want it, not by itself.

**Screenshots**
[Video Evidence](https://streamable.com/inasj3) (https://streamable.com/inasj3)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1909

**Additional context**
Installed from Windows 10 Store.

**Comment by ChrisAnd1998** [comment]
@Spud18 The new Acrylic navigation bar seems to be lagging on different builds of Windows 10. So if you move to window it will follow slowly a couple seconds later. This will be fixed next update. If you use the free version you can download the pre-release 1.5.7.0 which uses blur instead of acrylic which works better but i am planning on removing it completely.

**Comment by Spud18** [comment]
> @Spud18 The new Acrylic navigation bar seems to be lagging on different builds of Windows 10. So if you move to window it will follow slowly a couple seconds later. This will be fixed next update. If you use the free version you can download the pre-release 1.5.7.0 which uses blur instead of acrylic which works better but i am planning on removing it completely.

Thank you. I am currently using the paid Microsoft Store version. It's not a big problem, just a little weird. Thanks!
