### ISSUE TITLE
Action bar/Tray icon invisible after updating to 1.6.7.0

### ISSUE THREAD

**Issue by itsmeow** [ChrisAnd1998/TaskbarX#586]
**Describe the bug**
The icon in the tray is not visible, it's just an empty box.
I've tried fiddling with the "Show Tray icon" setting and applying/restarting/stopping TaskbarX. Nothing seems to fix it.
Clicking it does nothing, right-clicking it does nothing, middle-clicking it does nothing.

**To Reproduce**
1. Update to 1.6.7.0
2. Tray icon appears to be invisible.

**Expected behavior**
Icon should show as before

**Screenshots**
(I am hovering it in this screenshot)
![image](https://user-images.githubusercontent.com/10366817/112039439-6c75c480-8b1a-11eb-8462-405c1b827385.png)
![image](https://user-images.githubusercontent.com/10366817/112039490-7b5c7700-8b1a-11eb-8415-7d79e6b5016d.png)
After closing in Task Manager, it went away, so it is actually TaskbarX.
![image](https://user-images.githubusercontent.com/10366817/112039561-8ca58380-8b1a-11eb-8ac9-8909c17a89e7.png)
After restarting the program, it still doesn't appear properly.
![image](https://user-images.githubusercontent.com/10366817/112039593-962eeb80-8b1a-11eb-80cf-3bf16284e774.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro Insider Preview
 - Version: Dev (OS Build 21332.1000 - Windows 10 Feature Experience Pack 321.5601.0.3)

**Comment by ChrisAnd1998** [comment]
Ew, that didn't work out well... Even the icon in taskmanager is blank. I'll do some more adjustments to fix it.

**Comment by tGeanezini** [comment]
I'm having the same issue with the Origin icon.

![image](https://user-images.githubusercontent.com/4115601/112868326-5031d480-9092-11eb-88c1-fc2f38a10ada.png)

The app is open as seen on Task Manager but the icon is invisible on the tray and because of that I can't do anything with it.

![image](https://user-images.githubusercontent.com/4115601/112868867-ea921800-9092-11eb-9bc4-cff05ee4b104.png)

 Origin is set up not to open with Windows. Maybe this info can help with the investigation.

**Desktop (please complete the following information):**

OS: Windows 10 Pro
Version: 20H2 - OS Build 19042.867 - Windows Feature Experience Pack 120.2212.551.0

**Comment by GanerCodes** [comment]
![image](https://user-images.githubusercontent.com/34655998/136790520-439fdc36-1358-4123-a9c9-bd9f6635561b.png)
same here

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
