### ISSUE TITLE
Its not opening with Windows

### ISSUE THREAD

**Issue by Mirand8** [ChrisAnd1998/TaskbarX#614]
I have to open the program every time i start my pc

**Comment by laporeon** [comment]
Hey, have you figured out any solution? I have the same problem here. It was working fine, now everyime i start Windows, i have to restart TaskbarX too. Also, even when TaskbarX it's already started, if i open configurator, settings are not the ones i'm using, even tho they are correclty applied.

**Comment by Mirand8** [comment]
_> Hey, have you figured out any solution? I have the same problem here. It was working fine, now everyime i start Windows, i have to restart TaskbarX too. Also, even when TaskbarX it's already started, if i open configurator, settings are not the ones i'm using, even tho they are correclty applied._

No man, i didn't. I think the developer has not yet fixed the problem.

**Comment by laporeon** [comment]
Thanks for the answer.  I was using TaskbarX 1.6.8.0 and saw the update and did it. And ever since i updated to version 1.6.9.0, i'm having this problem. The odd thing is that i uninstalled version 1.6.9.0 using "Uninstall" inside TaskbarX to make sure that it'd be correctly uninstalled, then i reinstalled the previous version and it's not working too! I also tried 1.6.7.0. Same.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
