### ISSUE TITLE
Norton Antivirus removing important TaskbarX files

### ISSUE THREAD

**Issue by UltraProgrammer279** [ChrisAnd1998/TaskbarX#628]
**Description**
Norton Antivirus keeps deleting important files.

**To Reproduce**
Steps to reproduce the behaviour (make sure to do this on a Norton-protected computer):
1. Download the zip file
2. Extract the downloaded zip file
3. Now wait.
4. Then it says it's **not safe**.

**Expected behaviour**
It keeps the files.

**Desktop**
 - OS: Windows 10 64-bit
 - Windows 10 version: 20H2
 - Intel 64-bit processor

**Comment by VulpesPaw** [comment]
I know this is a basic question, but as you have not provided any information for it, alas here we are.

Have you tried to add TaskbarX to Norton exclusions?
You should be able to add both TaskbarX as a file exclusion as well as a running process exclusion.
(you can in most antivirus software at least)

Otherwise, here's a guide to add file exclusions with Norton: https://support.norton.com/sp/en/us/home/current/solutions/v3672136 

Hope this helps, 
Cheers FoxPaw

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
