### ISSUE TITLE
I cannot disable/uninstall TaskBarX, I keep trying to find a way but it is not working out at all.. Version: 1.6.9.0 OS: Windows 10 Pro, please help!

### ISSUE THREAD

**Issue by ItzDaPotato** [ChrisAnd1998/TaskbarX#655]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 1909]

**Additional context**

**Comment by LukoFoks** [comment]
Since you haven't filled out the form, it is hard to tell what is really happening. I will try to assist you.

1. Open Windows search (Win + S)
2. Type "TaskbarX Configurator"
3. In the left menu, click on Uninstall

After the uninstallation Windows Explorer shows up. You should be located in the installation folder with "TaskbarX.exe" and so on. If not, navigate to your installation folder yourself. Delete the whole folder.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
