### ISSUE TITLE
Just a question: Will TaskbarX stop on the upcoming windows 11?

### ISSUE THREAD

**Issue by AbedYamout** [ChrisAnd1998/TaskbarX#681]
Will TaskbarX stop working since the upcoming windows 11 already have an option to center the taskbar in the settings?

**Comment by ChrisAnd1998** [comment]
Well the centering feature will indeed stop working however the taskbar styling will still work.
For Win 11 I might start fresh with a new program **TaskbarXI** which focusses on other requested features and includes the taskbar styling features.

**Comment by rashil2000** [comment]
Hi @ChrisAnd1998 , thanks for this response, but in Windows 11, the state of centering stuff is a little different. In the Settings app, if we select Center alignment, then all icons, including Start button, search, task view and the app icons get centered. If we select Left alignment, they're all in the left. 
Now, the first scenario isn't very ideal, because people generally only want app icons to get centered, but not the Start button (this might be because of almost 25 years of muscle memory, and also, Start button in the center does not follow [Fitt's Law](https://en.wikipedia.org/wiki/Fitts%27s_law)). So naturally, when I first booted up Windows 11 I selected the Left alignment and trusted dear TaskbarX to handle the app icons in the centre. But it didn't work :(
Hoping this gets fixed...

**Comment by AbedYamout** [comment]
@ChrisAnd1998 I hope TaskbarXI gets released before windows 11 or at the same day 😁
@rashil2000 yes that's what I was talking about.

**Comment by yokhoe** [comment]
> 
> 
> Well the centering feature will indeed stop working however the taskbar styling will still work.
> For Win 11 I might start fresh with a new program **TaskbarXI** which focusses on other requested features and includes the taskbar styling features.
> 
> https://github.com/ChrisAnd1998/TaskbarXI

Thank you regardless for your work on this, Chris. At the very least, your effort probably butterfly effect Microsoft to consider the UI decision on Win11.

**Comment by ScootZilla** [comment]
I see more and more comments on the net, that lots of computers do not pass Microsoft's Health Check which indicates whether they are qualified to upgrade to Windows 11. One big hurdle could be the lack of a TPM chip. For all those who don't want to buy a new machine it would be great if development of TaskbarX will continue. I for my own would at least like to see fixes for TaskbarX's increasing memory consumption (with each application start it fetches some RAM but it does never release it) and the pixel issue which recently was determined.

So please keep up the good work on your tool - maybe we will even see a switch which offers the option to have the Start button being centered.

**Comment by assassinliujie** [comment]
i still need the transparent taskbar

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
