### ISSUE TITLE
Taskbar margin on win10

### ISSUE THREAD

**Issue by KIttojo** [ChrisAnd1998/TaskbarX#685]
A 1 pixel bottom margin appeared few updates ago. I tried to reinstall taskbar and update it, but it didn't help me. My win10 version - 10H2. 
Here is image:
![Untitled](https://user-images.githubusercontent.com/45813478/122668027-d6a41100-d1be-11eb-8c4c-abc48ac79618.png)

**Comment by SpeedK** [comment]
Same. Just installed the software and this happens. Testing taskbar settings, this bug mostly disappears if you use small taskbar buttons in your taskbar settings. I say "mostly" because the bug is still visible at the right bottom corner of the screen. It looks like the taskbar doesn't fit to the screen considering that when I try to use the "show desktop" button moving the mouse at coordinate 1920x1080 (bottom right), the click doesn't go through and clicks directly the desktop behind the bar.

**Comment by WesleyM77** [comment]
Seeing the same thing on my desktop.

**Comment by meiaihara06** [comment]
fixed in [1.7.1.0](https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.7.1.0)

check out #682

**Comment by RafeeDaBoy** [comment]
@meiaihara06 Faced the same issue, do I download the release.zip file?

**Comment by meiaihara06** [comment]
it is a pre-release
and rainmeter skin and other versions seem to come with releases i think.
so i think we should wait for release (?)
personally i use 1.6.9 now because of another bug. but if you are on windows and you want to use 1.7.0, yes. it is the only option available for now.

**Comment by SpeedK** [comment]
> fixed in [1.7.1.0](https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.7.1.0)
> 
> check out #682

What about the valid digital signature?

**Comment by meiaihara06** [comment]
i don't know, I'm just trying to clarify as much as i can , I'm not collaborator or member of repository.
ask members of repo about this.
Thanks!

**Comment by ChrisAnd1998** [comment]
Fixed
