### ISSUE TITLE
Windows Button Doesn't Work Anymore In Bottom Left Corner

### ISSUE THREAD

**Issue by simonferndriger** [ChrisAnd1998/TaskbarX#699]
**To Reproduce**
1. Move mouse cursor in the bottom left corner (I do this normally to be very fast on the Windows button)
2. Click
3. Start menu does NOT open

**Expected behavior**
Start menu should open

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H1

**Comment by StrickerBR** [comment]
I've noticed the same problem, and prefered to add here insted of creating a new issue post.
It seems there are a 1 pixel line off set of the taskbar from the edge of the screen. i've seem because i use blur and in bright screens i can see the single line without blur, and it had also affected the start menu, since if i put the cursor glued to the left border it can click the button, but if glue it to the bottom edge it wont.

**Desktop:**

- OS: Windows 10
- Version 20H2

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
