### ISSUE TITLE
taskbar centering but not being transparent in boot

### ISSUE THREAD

**Issue by skultzz** [ChrisAnd1998/TaskbarX#724]
when I turn on the pc the taskbar centralizes and becomes transparent, but after 5 seconds there is a "refresh" and it is no longer transparent

**Comment by Asad-13** [comment]
That happened with me on using 1.7 for the first couple of days. I used to just install the latest version of TaskbarX, set the appearance of the taskbar, and leave it at that. No fiddling with other settings. But since 1.7, the same thing happened with me when I booted up my PC. So I went into the 'Startup' section and clicked on 'Create' and then on Apply. Then I closed it and since then, I haven't had that problem. So I guess it was done automatically on older versions but now you have to do it manually.

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
