### ISSUE TITLE
taskbar x don't center

### ISSUE THREAD

**Issue by legendsscars** [ChrisAnd1998/TaskbarX#809]
**Describe the bug**
don't center when i lauch it

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/91395811/134788155-bbe0fe3e-4b55-45b6-80d1-647af9d14116.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [e.g. 21H1]

**Additional context**

**Comment by valinet** [comment]
It's probably because of TaskbarX not taking into account when the "News and interests" panel is not displayed. Described [here](https://github.com/ChrisAnd1998/TaskbarX/pull/820).

An archive with fixed binaries according to the PR I made: [TaskbarX.zip](https://github.com/valinet/ExplorerPatcher/files/7271525/TaskbarX.zip).

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
