### ISSUE TITLE
TaskbarX wont centar icons on my primary monitor (I have 3)

### ISSUE THREAD

**Issue by akisha009** [ChrisAnd1998/TaskbarX#811]
![Screenshot_1](https://user-images.githubusercontent.com/91568304/135158393-7458a75f-15d9-4bc4-a60b-23c84e108740.png)
I just installed new windows, before the installation I had 3 monitors and it all worked
Other 2 taskbars centar icons

**Comment by valinet** [comment]
It's probably because of TaskbarX not taking into account when the "News and interests" panel is not displayed. Described [here](https://github.com/ChrisAnd1998/TaskbarX/pull/820).

**Comment by valinet** [comment]
It's probably because of TaskbarX not taking into account when the "News and interests" panel is not displayed. Described [here](https://github.com/ChrisAnd1998/TaskbarX/pull/820).

An archive with fixed binaries according to the PR I made: [TaskbarX.zip](https://github.com/valinet/ExplorerPatcher/files/7271525/TaskbarX.zip).

**Comment by ChrisAnd1998** [comment]
Please try the pre-release 1.7.4.0
