### ISSUE TITLE
my primary monitor don't center

### ISSUE THREAD

**Issue by ztheback** [ChrisAnd1998/TaskbarX#818]
**Describe the bug**

**To Reproduce**
1. I open task Bar x , and my primary monitor don't center.

**Expected behavior**
He don't center ;-;

**Screenshots**

![image](https://user-images.githubusercontent.com/90469037/135605352-9e583aaf-435b-4bd2-8cb1-49a26ea80ecc.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 64 bits]
 - Version [2004]

**Comment by valinet** [comment]
It's probably because of TaskbarX not taking into account when the "News and interests" panel is not displayed. Described [here](https://github.com/ChrisAnd1998/TaskbarX/pull/820).

**Comment by valinet** [comment]
It's probably because of TaskbarX not taking into account when the "News and interests" panel is not displayed. Described [here](https://github.com/ChrisAnd1998/TaskbarX/pull/820).

An archive with fixed binaries according to the PR I made: [TaskbarX.zip](https://github.com/valinet/ExplorerPatcher/files/7271525/TaskbarX.zip).

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
