### ISSUE TITLE
Taskbaricons not centering 21H1

### ISSUE THREAD

**Issue by M3MM3L** [ChrisAnd1998/TaskbarX#819]
Hi,

i got on my latest installation of Windows an error while using TaskbarX.
Transparancy and animations are working fine, but the icons are not centered..

Console output: "@Calculator | The object reference was not set to an object instance"
![grafik](https://user-images.githubusercontent.com/50866235/135672228-0c60baca-448b-4b5b-8b6c-e0c069e3b0d8.png)

Windows10
21H1 19043.928

**Comment by valinet** [comment]
It's probably because of TaskbarX not taking into account when the "News and interests" panel is not displayed. Described [here](https://github.com/ChrisAnd1998/TaskbarX/pull/820).

**Comment by valinet** [comment]
It's probably because of TaskbarX not taking into account when the "News and interests" panel is not displayed. Described [here](https://github.com/ChrisAnd1998/TaskbarX/pull/820).

An archive with fixed binaries according to the PR I made: [TaskbarX.zip](https://github.com/valinet/ExplorerPatcher/files/7271525/TaskbarX.zip).

**Comment by Dschogo** [comment]
Getting this all the time. Sometimes there was `"@calculator | The object reference was not set to an object instance"`
But that got "fixed" by ur PR.
Due to that, ima add this here as a comment.

```
Waiting for Shell_TrayWnd
@Calculator | Error: Missing method 'instance object [TaskbarX] Accessibility.IAccessible::get_accRole(object)' from class 'System.Int32'.
@Looper1 | Error: Missing method 'instance object [TaskbarX] Accessibility.IAccessible::get_accRole(object)' from class 'System.Int32'.
```

Edition	Windows 10 Pro
Version	21H1
Installed on	‎29.‎10.‎2020
OS build	19043.1237
Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by Kaization** [comment]
> 
> 
> It's probably because of TaskbarX not taking into account when the "News and interests" panel is not displayed. Described [here](https://github.com/ChrisAnd1998/TaskbarX/pull/820).
> 
> An archive with fixed binaries according to the PR I made: [TaskbarX.zip](https://github.com/valinet/ExplorerPatcher/files/7271525/TaskbarX.zip).

Tysm this helped my issue
