### ISSUE TITLE
https://taskbarx.net/

### ISSUE THREAD

**Issue by gDansel** [ChrisAnd1998/TaskbarX#845]
You aware of this site? Seems like someone is trying present your software as theirs.

**Comment by ChrisAnd1998** [comment]
@gDansel I see... Nothing happens if i hit the download button though... The footer says `TaskbarX FanSite` and the about page says `Hi! My name is Anna and I want to tell you about this awesome app I found. I was having trouble balancing my work and also studying for my exams, which was taking away a lot of time I could spend on my other hobbies. My friend recommended TaskbarX app to me and I downloaded it right away. I was surprised by how many useful tools it had. I can use it to organize my to-do lists, collaborate with my fellow students, keep track of my exams, and even make diagrams. It's really easy to use and I can't believe I've been missing out on it for so long. I recommend this app to anyone who wants to get more done, at school or at work. I hope you're also having fun using it!`

If it really is just a fan page I am fine with it.

**Comment by gDansel** [comment]
Some of the writing seems kinda odd though, doesn't really fit what the software actually does. I mean: "collaborate with my fellow students"? I noticed the links were dead too, but yeah, I'd keep an eye on it.

**Comment by rayzr522** [comment]
definitely a scam site:
- clicking the download redirects to https://games2k20.com/games/misc/taskbarx-app?utm_source=bing&utm_medium=afs&utm_campaign=AFTaskX2
- a large majority of the site is written to make it sound like they are the authors
- the site seems half-assed with broken links and sloppy markup, yet they went to the effort of setting up a GTM container on the page

seems like either an attempt to get users onto a scam site to get them to download malicious software, to earn ad profit/referral bonuses off of the hard work of another -- you -- or simply an attempt to harvest information about users. i have a hard time believing this is just a "fansite"

**Comment by ChrisAnd1998** [comment]
I see now.. They have changed the content now.

**Comment by rayzr522** [comment]
I'd recommend reaching out to namecheap (the domain regsitrar of this domain) as well as cloudflare and reporting the site. both companies have a place you can report abuse and they're generally quite good about taking sites down

**Comment by gDansel** [comment]
Given the recent mention on that LTT video getting the site down quick might be more important too. It's been SEO'd to hell and back so it's the top hit.

**Comment by ChrisAnd1998** [comment]
@rayzr522 Thanks for the heads up. I just submitted a abuse report.

**Comment by ChrisAnd1998** [comment]
@gDansel That's true but Google should see the large amount of organic traffic which should defeat their SEO on Google at least.

**Comment by Romloader** [comment]
Worth mentioning just as info that the website now makes you land on some sort of chrome extension website called UpMyChrome where apparently an extension/plugin called "TaskbarX" is listed
