### ISSUE TITLE
Taskbar Configurator app does not effect taskbar

### ISSUE THREAD

**Issue by Woofer21** [ChrisAnd1998/TaskbarX#895]
**Describe the bug**
When applying settings through the TaskbarX Configurator it will not affect the taskbar, then running the taskbarX.exe application will only center the taskbar.

**To Reproduce**
1. Go to the configurator and make changes
2. Click on apply
3. observe how it does nothing
4. run the taskbarX.exe file
5.  observe how it only centers taskbar

**Expected behavior**
the config actions take effect and my taskbar becomes customized

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version 19043.1415
 - App Version 1.7.6.0

**Comment by HCBBSU** [comment]
Same issue with same OS and version.

**Comment by HCBBSU** [comment]
> Same issue with same OS and version.

Huh. It looks as if my Windows 10... activated itself? Which probably supersedes TaskbarX's configuration. While the icons are centered, opening new icons does not result in an adjustment in the icon centering.

**Comment by s0meone247** [comment]
I have the same problem, except I'm on windows 10 pro, 19044.1503

**Comment by Pablokiryu** [comment]
Same issue. 
Version: Windows 10 Pro
Build : 19043.1526 
App version : 1.7.6..0

**Comment by Lino5000** [comment]
I've got what seems like the same problem, but I've found that it only happens if I open the programs from the start menu; if I actually go to the folder in explorer (or a terminal) and run the .exe files from there it fixes it. 

In my case, it behaves similarly to how #677 describes that issue, with the Configurator not working because pressing "Apply" crashes the TaskbarX process if either was opened using the start-menu shortcuts.

OS: Windows 10 Home
Build: 19043.1586
App Version: 1.7.6.0 (portable)

**Comment by KoroPVP** [comment]
> I've got what seems like the same problem, but I've found that it only happens if I open the programs from the start menu; if I actually go to the folder in explorer (or a terminal) and run the .exe files from there it fixes it.
> 
> In my case, it behaves similarly to how #677 describes that issue, with the Configurator not working because pressing "Apply" crashes the TaskbarX process if either was opened using the start-menu shortcuts.
> 
> OS: Windows 10 Home Build: 19043.1586 App Version: 1.7.6.0 (portable)

BRO TYSM ISTG YOUR AMAZING

**Comment by Woofer21** [comment]
No longer on windows 10, closing
