### ISSUE TITLE
when running taskbarx as transparent, taskbar is transparent through all programs down to desktop

### ISSUE THREAD

**Issue by DasDouble** [ChrisAnd1998/TaskbarX#908]
See screenshot below.

This is how it looks, when I've opened a program (unnormal)
![image](https://user-images.githubusercontent.com/77044936/153048100-ed4fe0e3-b998-4587-b051-3d814cfc471e.png)

And this is how it looks when github closed (normal)
![image](https://user-images.githubusercontent.com/77044936/153048256-e694d5cd-495b-4b3e-8192-db010da33d84.png)

**Comment by DasDouble** [comment]
Ah I think I've fixed it by making the taskbar disappear! OH WOW THIS IS NOW AWESOME!!!

**Comment by Sakooooo** [comment]
this is normal though?

**Comment by Varachack** [comment]
Your Google Chrome window is above the taskbar. Your TaskbarX window is not, so you are seeing this part of the TaskbarX window through the taskbar because it is **transparent.** You didn’t reposition the TaskbarX window above the taskbar, so you will see that portion of the TaskbarX window regardless of any window that is above it. This will occur with any window that is inside or underneath the taskbar.

Reposition your windows accordingly.
