### ISSUE TITLE
I have to start it manually on every startup!!!!!

### ISSUE THREAD

**Issue by dwaparr** [ChrisAnd1998/TaskbarX#928]
Hi! Great work with the project...
But I have one problem, it does not start automatically on every start-up.
Hope you will come up with a solution

 - OS: Windows 10 Pro
 - Version 21H1

**Comment by Caravet** [comment]
Hi dwaparr,

I had this problem too, but fixed it by following these steps

Opening the _Windows_ _task scheduler_ program and disabling or removing any existing _TaskbarX_ entries
Increasing the startup lead time to 60 seconds instead of 6 in the Startup submenu in the _TaskbarX_ configuration

Seems to be working for me now! I'll come back again if it doesn't.
